note
	description: "[
		Turns a reader's page indicator into a file name, so a saved screenshot
		is identifiable by what the reader was showing rather than by a counter
		that means nothing outside this program.

		    "Page 90-92 of 139"   ->   ocr_Page_90-92_of_139.png
		    "83-85 / 238"         ->   ocr_83-85_238.png
		    "Page iii of 214"     ->   ocr_Page_iii_of_214.png
	]"
	design: "[
		Indicators are OCR output, so they can contain anything at all - including
		every character Windows forbids in a file name. The oblique in "90-92 / 139"
		is the ordinary case, not an edge case: left alone it would be read as a
		directory separator and the write would fail or land somewhere unintended.

		So the transformation is a whitelist, not a blacklist. Letters, digits
		and hyphens survive; everything else becomes an underscore, runs of
		underscores collapse, and the result is capped. A whitelist cannot be
		outflanked by a character nobody thought of, which matters when the
		input is generated by a language model.
	]"

class
	OCR_IMAGE_NAME

feature -- Conversion

	stem (a_label: READABLE_STRING_32; a_index: INTEGER): STRING_32
			-- File-name stem for a capture showing `a_label'.
			--
			-- Falls back to the zero-padded `a_index' when there is no indicator
			-- to name it by, or when the indicator reduces to nothing usable.
		do
			Result := sanitized (a_label)
			if Result.is_empty then
				Result := padded (a_index)
			end
		ensure
			non_empty: not Result.is_empty
		end

	sanitized (a_text: READABLE_STRING_32): STRING_32
			-- `a_text' reduced to letters, digits, hyphens and single
			-- underscores, capped at `Maximum_length'.
		local
			l_underscore: BOOLEAN
		do
			create Result.make (a_text.count.min (Maximum_length))
			across a_text as ic_char loop
				if Result.count < Maximum_length then
					if is_safe (ic_char.item) then
						Result.append_character (ic_char.item)
						l_underscore := False
					elseif not l_underscore and then not Result.is_empty then
						Result.append_character ('_')
						l_underscore := True
					end
				end
			end
				-- A trailing underscore would come from the label ending in
				-- punctuation, and reads as a mistake in a directory listing.
			from
			until
				Result.is_empty or else Result.item (Result.count) /= '_'
			loop
				Result.remove_tail (1)
			end
		ensure
			within_cap: Result.count <= Maximum_length
		end

	padded (a_index: INTEGER): STRING_32
			-- `a_index' as at least four digits, so counter-named files still
			-- sort in capture order.
		do
			create Result.make_from_string_general (a_index.out)
			from
			until
				Result.count >= 4
			loop
				Result.precede ('0')
			end
		ensure
			wide_enough: Result.count >= 4
		end

feature {NONE} -- Implementation

	is_safe (a_char: CHARACTER_32): BOOLEAN
			-- May `a_char' appear in a file name unchanged?
			--
			-- Deliberately narrow. Accented letters and other scripts are
			-- excluded not because Windows rejects them but because a name that
			-- survives a round trip through a shell, a zip file and someone
			-- else's machine is worth more here than a faithful one.
		do
			Result := (a_char >= 'a' and a_char <= 'z')
				or (a_char >= 'A' and a_char <= 'Z')
				or (a_char >= '0' and a_char <= '9')
				or a_char = '-'
		end

feature -- Constants

	Maximum_length: INTEGER = 60
			-- Longest stem produced. Leaves room for the folder, the "ocr_"
			-- prefix, a collision suffix and the extension inside the path
			-- limits that still bite on Windows.

end
